import { StyleSheet, Dimensions } from 'react-native';
import appTheme from '../../utils/Theme';

const { COLORS, SIZES, FONTS } = appTheme;
const { height, width } = Dimensions.get('window');

export default StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeAreaStyle: {
    backgroundColor: 'transparent',
  },
  mainBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  flatListStyle: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  backgroundImageStyle: {
    opacity: 0.9,
  },
  headerContainer1: {
    backgroundColor: COLORS.primary,
    paddingBottom: SIZES.padding * 1.5,
    borderBottomLeftRadius: SIZES.radius_lg,
    borderBottomRightRadius: SIZES.radius_lg,
    elevation: 8,
    shadowColor: COLORS.dark,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    position: 'relative',
  },
  topHeaderSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    paddingTop: SIZES.padding / 1.5,
    paddingBottom: SIZES.padding / 2,
  },
  faqIconContainer: {
    backgroundColor: COLORS.secondary,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding / 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  menuIconContainer: {
    backgroundColor: COLORS.secondary,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding / 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  mainHeaderSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SIZES.padding,
    paddingVertical: SIZES.padding / 1.5,
    marginTop: -SIZES.margin,
  },
  logoContainer: {
    marginRight: SIZES.margin,
    backgroundColor: COLORS.primaryLight,
    borderRadius: SIZES.radius_lg,
    padding: 1,
  },
  headerLogo: {
    width: SIZES.h2 * 4,
    height: SIZES.h2 * 4,
  },
  companyNameContainer: {
    alignItems: 'center',
  },
  companyName: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    letterSpacing: 1,
  },
  companySubtitle: {
    fontSize: SIZES.font,
    fontFamily: FONTS.font.fontFamily,
    lineHeight: FONTS.font.lineHeight,
    fontWeight: FONTS.subheading.fontWeight,
    color: COLORS.title,
    marginTop: SIZES.margin / 4,
  },
  rateTimestampContainer: {
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    marginTop: SIZES.margin / 2,
  },
  rateTimestamp: {
    fontSize: SIZES.fontSm,
    fontFamily: FONTS.fontSm.fontFamily,
    lineHeight: FONTS.fontSm.lineHeight,
    color: COLORS.title,
    fontWeight: FONTS.subheading.fontWeight,
    opacity: 0.85,
    textShadowColor: COLORS.dark,
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
  },
  rateCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SIZES.padding,
    marginTop: SIZES.margin,
  },
  rateCard: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: SIZES.radius_lg,
    marginHorizontal: SIZES.margin / 2,
    padding: SIZES.padding,
    elevation: 6,
    shadowColor: COLORS.dark,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
  },
  rateCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rateIconContainer: {
    marginRight: SIZES.margin / 1.5,
  },
  animatedCoinContainer: {
    height: SIZES.h4 * 1.5,
    width: SIZES.h4 * 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primaryLight,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    transform: [{ perspective: 1000 }],
  },
  rateCoinIcon: {
    width: SIZES.h4,
    height: SIZES.h4,
    resizeMode: 'contain',
  },
  rateTextContainer: {
    flex: 1,
  },
  rateLabel: {
    fontSize: SIZES.fontSm,
    fontFamily: FONTS.fontSm.fontFamily,
    lineHeight: FONTS.fontSm.lineHeight,
    color: COLORS.textLight,
    fontWeight: FONTS.subheading.fontWeight,
    marginBottom: SIZES.margin / 4,
  },
  rateValue: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.success,
    fontWeight: FONTS.heading.fontWeight,
    marginBottom: SIZES.margin / 8,
  },
  rateUnit: {
    fontSize: SIZES.fontXs,
    fontFamily: FONTS.fontXs.fontFamily,
    lineHeight: FONTS.fontXs.lineHeight,
    color: COLORS.textLight,
    fontWeight: FONTS.subheading.fontWeight,
  },
  sectionHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.margin / 1.5,
  },
  titletext: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    letterSpacing: 1,
  },
  viewAllText: {
    textAlign: 'right',
    marginRight: SIZES.margin,
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    letterSpacing: 1,
  },
  leftIconPadding: {
    paddingLeft: SIZES.padding / 2,
    paddingRight: SIZES.padding * 1.5,
  },
  scrollViewStyle: {
    marginTop: SIZES.margin,
    backgroundColor: COLORS.background,
  },
  grayBackground: {
    backgroundColor: COLORS.white,
  },
  caroselContainer: {
    width: '100%',
    height: height * 0.3,
    position: 'relative',
    padding: 10,
    borderRadius: SIZES.radius_lg * 2,
    overflow: 'hidden',
    marginTop: SIZES.margin,
    marginBottom: -SIZES.margin,
    alignItems: 'center',
  },
  caroselStyle: {
    width,
    height: height * 0.3,
    borderRadius: SIZES.radius_lg * 2,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    paddingVertical: SIZES.padding / 1.5,
  },
  headercontainer1: {
    backgroundColor: COLORS.primary,
  },
  locationWrapper: {
    alignItems: 'flex-start',
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  notificationIconWrapper: {
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
  },
  locationText: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    marginLeft: SIZES.margin / 2,
    marginRight: SIZES.margin / 2,
  },
  notificationIcon: {
    marginLeft: SIZES.margin / 2,
    padding: SIZES.padding / 1.5,
  },
  locationLabel: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.textLight,
    marginBottom: SIZES.margin / 2,
    padding: SIZES.padding / 2,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: SIZES.margin,
    marginLeft: 0,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: SIZES.radius,
    marginHorizontal: SIZES.margin,
    marginTop: SIZES.margin / 1.5,
    padding: SIZES.padding,
    shadowColor: COLORS.dark,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  searchInput: {
    flex: 1,
    marginLeft: SIZES.margin / 1.5,
    color: COLORS.text,
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
  },
  menuDrawerContainer: {
    position: 'absolute',
    top: '10%',
    left: '2%',
  },
  imgResponsive: {
    flex: 1,
    width: undefined,
    height: undefined,
  },
  headingText: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
  },
  itemCardContainer: {
    width: SIZES.container / 2.5,
    height: SIZES.h1 * 5,
    marginTop: SIZES.margin / 2,
    marginRight: SIZES.margin * 1.5,
  },
  productgoldContainer: {
    paddingLeft: SIZES.padding / 1.5,
  },
  iconContainer: {
    width: SIZES.h2 * 2,
    height: SIZES.h2 * 2,
    marginRight: SIZES.margin * 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.radius_lg,
    overflow: 'hidden',
    backgroundColor: COLORS.primaryLight,
    marginTop: SIZES.margin,
  },
  iconImage: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    resizeMode: 'cover',
  },
  categoryContainer: {
    marginTop: SIZES.margin / 1.5,
    paddingHorizontal: SIZES.padding / 1.5,
  },
  titleSpacer: {
    marginLeft: '5%',
    marginTop: SIZES.margin / 1.5,
  },
  productCard: {
    marginLeft: '5%',
    width: '43%',
    height: SIZES.h1 * 5,
    marginTop: SIZES.margin / 1.5,
    marginBottom: SIZES.margin,
    borderColor: COLORS.white,
    borderWidth: SIZES.radius,
  },
  productScrollContainer: {
    marginTop: SIZES.margin / 1.5,
  },
  seeAllTextContainer: {
    flex: 1,
    alignItems: 'flex-end',
    marginTop: SIZES.margin,
  },
  locationImage: {
    width: SIZES.h2 * 2,
    height: SIZES.h3 * 2,
    marginRight: SIZES.margin / 2,
  },
  seeAllText: {
    textAlign: 'right',
    marginRight: '6%',
    marginTop: -SIZES.h3,
  },
  spacer: {
    marginBottom: SIZES.margin / 2,
  },
  categoryWrapper: {
    alignItems: 'center',
    marginRight: SIZES.margin,
    padding: 0,
    marginLeft: -SIZES.margin / 2,
  },
  container: {
    padding: 5,
  },
  title: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    marginLeft: SIZES.margin / 1.5,
  },
  titlecard: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.success,
    marginLeft: '5%',
  },
  trendingContainer: {
    flexDirection: 'row',
    marginTop: SIZES.margin / 1.5,
  },
  card: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: SIZES.radius,
    padding: SIZES.padding,
    margin: SIZES.margin / 1.5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  subtitle: {
    color: COLORS.success,
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    marginLeft: '5%',
  },
  subtitle1: {
    color: COLORS.success,
    fontSize: SIZES.fontXs,
    fontFamily: FONTS.fontXs.fontFamily,
    lineHeight: FONTS.fontXs.lineHeight,
    marginLeft: '5%',
  },
  logo: {
    width: SIZES.h5,
    height: SIZES.h5,
    marginBottom: SIZES.margin / 1.5,
    marginRight: SIZES.margin / 1.5,
    resizeMode: 'contain',
  },
  backgroundImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rateUpdatedText: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.title,
    marginTop: SIZES.margin / 2,
    textAlign: 'center',
    fontWeight: FONTS.heading.fontWeight,
  },
  contentWrapper: {
    marginHorizontal: SIZES.margin,
    marginTop: SIZES.margin,
    paddingVertical: SIZES.padding,
    paddingHorizontal: SIZES.padding,
    backgroundColor: COLORS.surfaceVariant,
    borderRadius: SIZES.radius_lg,
    elevation: 4,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3.5,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
  },
  contentText: {
    color: COLORS.title,
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    marginVertical: SIZES.margin / 2,
    textAlign: 'left',
    letterSpacing: 0.3,
  },
  contentText1: {
    color: COLORS.textLight,
    fontSize: SIZES.fontSm,
    fontFamily: FONTS.fontSm.fontFamily,
    lineHeight: SIZES.fontLg,
    fontWeight: FONTS.subheading.fontWeight,
    opacity: 0.9,
  },
  animatedContainer: {
    height: SIZES.h5,
    width: SIZES.h5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SIZES.margin / 1.5,
    overflow: 'hidden',
    transform: [{ perspective: 1000 }],
  },
  youtubeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
});