import { StyleSheet, Dimensions } from 'react-native';
import appTheme from '../../utils/Theme';

const { COLORS, SIZES } = appTheme;
const { height, width } = Dimensions.get('window');

export default StyleSheet.create({
  flex: {
    flex: 1,
  },
  safeAreaStyle: {
    backgroundColor: 'transparent',
  },
  mainBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.background,
  },
  flatListStyle: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  backgroundImageStyle: {
    opacity: 0.9,
  },
  headerContainer1: {
    backgroundColor: COLORS.primary,
    paddingBottom: SIZES.padding * 1.5,
    borderBottomLeftRadius: SIZES.radius_lg,
    borderBottomRightRadius: SIZES.radius_lg,
    elevation: 8,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    position: 'relative',
    height: 250,
  },
  topHeaderSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    paddingTop: SIZES.padding / 1.5,
    paddingBottom: SIZES.padding / 2,
  },
  faqIconContainer: {
    backgroundColor: COLORS.secondary,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding / 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  menuIconContainer: {
    backgroundColor: COLORS.secondary,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding / 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  mainHeaderSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    paddingHorizontal: SIZES.padding,
    paddingVertical: SIZES.padding / 1.5,
    marginTop: -SIZES.margin * 5.5,
  },
  logoContainer: {
    marginRight: -SIZES.margin * 4,
    padding: 1,
  },
  headerLogo: {
    width: SIZES.h4 * 4, // Changed from h2 to h4 to avoid potential object reference
    height: SIZES.h4 * 4,
  },
  companyNameContainer: {
    alignItems: 'center',
    marginRight: SIZES.margin,
  },
  companyName: {
    fontSize: SIZES.h5,
    fontFamily: 'Poppins-Bold',
    fontWeight: '700',
    color: COLORS.background,
    letterSpacing: 1,
  },
  companySubtitle: {
    fontSize: SIZES.font,
    fontFamily: 'TimesNewRoman',
    fontWeight: '500',
    color: COLORS.title,
    marginTop: SIZES.margin / 4,
  },
  rateTimestampContainer: {
    alignItems: 'center',
    paddingHorizontal: SIZES.padding,
    marginTop: SIZES.margin / 2,
  },
  rateTimestamp: {
    fontSize: SIZES.fontSm,
    fontFamily: 'TimesNewRoman',
    color: COLORS.background,
    fontWeight: '500',
    opacity: 0.85,
    textShadowColor: COLORS.shadow,
    textShadowOffset: { width: 0.5, height: 0.5 },
    textShadowRadius: 1,
  },
  rateCardsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SIZES.padding,
    marginTop: SIZES.margin,
  },
  rateCard: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: SIZES.radius_lg,
    marginHorizontal: SIZES.margin / 2,
    padding: SIZES.padding,
    elevation: 6,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
  },
  rateCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rateIconContainer: {
    marginRight: SIZES.margin / 1.5,
  },
  animatedCoinContainer: {
    height: SIZES.h4 * 1.5,
    width: SIZES.h4 * 1.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.primaryLight,
    borderRadius: SIZES.radius,
    overflow: 'hidden',
    transform: [{ perspective: 1000 }],
  },
  rateCoinIcon: {
    width: SIZES.h4,
    height: SIZES.h4,
    resizeMode: 'contain',
  },
  rateTextContainer: {
    flex: 1,
  },
  rateLabel: {
    fontSize: SIZES.fontSm,
    fontFamily: 'TimesNewRoman',
    color: COLORS.textLight,
    fontWeight: '500',
    marginBottom: SIZES.margin / 4,
  },
  rateValue: {
    fontSize: SIZES.fontLg,
    fontFamily: 'TimesNewRoman',
    color: COLORS.success,
    fontWeight: '700',
    marginBottom: SIZES.margin / 8,
  },
  rateUnit: {
    fontSize: SIZES.fontXs,
    fontFamily: 'TimesNewRoman',
    color: COLORS.textLight,
    fontWeight: '500',
  },
  sectionHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SIZES.margin / 1.5,
  },
  titletext: {
    fontSize: SIZES.fontLg,
    fontFamily: 'TimesNewRoman',
    fontWeight: '700',
    color: COLORS.title,
    letterSpacing: 1,
    paddingLeft: 20,
  },
  viewAllText: {
    textAlign: 'right',
    marginRight: SIZES.margin,
    fontSize: SIZES.fontLg,
    fontFamily: 'TimesNewRoman',
    fontWeight: '700',
    color: COLORS.title,
    letterSpacing: 1,
  },
  titleSpacer: {
    // marginLeft: '5%',
    marginTop: SIZES.margin / 1.5,
  },
  productScrollContainer: {
    marginTop: SIZES.margin / 1.5,
    flexDirection: 'row',
    overflow: 'hidden',
    marginLeft: SIZES.margin / 1.5,

  },
  productgoldContainer: {
    paddingLeft: SIZES.padding / 1.5,
  },
  itemCardContainer: {
    // width: 160, // Fixed value instead of SIZES.container which might be an object
    // height: 200, // Fixed value instead of SIZES.h1 which might be an object
    marginTop: SIZES.margin / 2,
    marginRight: SIZES.margin * 1.5,
  },
  contentWrapper: {
    marginHorizontal: SIZES.margin,
    marginTop: SIZES.margin,
    paddingVertical: SIZES.padding,
    paddingHorizontal: SIZES.padding,
    backgroundColor: COLORS.surfaceVariant,
    borderRadius: SIZES.radius_lg,
    elevation: 4,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3.5,
    borderWidth: 1,
    borderColor: COLORS.borderColor,
  },
  contentText: {
    color: COLORS.title,
    fontSize: SIZES.fontLg,
    fontFamily: 'TimesNewRoman',
    fontWeight: '700',
    marginVertical: SIZES.margin / 2,
    textAlign: 'left',
    letterSpacing: 0.3,
  },
  contentText1: {
    color: COLORS.textLight,
    fontSize: SIZES.fontSm,
    fontFamily: 'TimesNewRoman',
    opacity: 0.9,
  },
  youtubeContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  youtubeWrapper: {
    width: '100%',
    paddingHorizontal: SIZES.padding,
    marginBottom: 10,
  },
});