import { StyleSheet, Dimensions } from 'react-native';
import appTheme from '../../utils/Theme';

const { COLORS, SIZES, FONTS } = appTheme;
const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingBottom: SIZES.margin,
  },
  header: {
    padding: SIZES.padding,
    paddingTop: SIZES.padding,
    paddingBottom: SIZES.padding * 1.5,
    borderBottomLeftRadius: SIZES.radius_lg * 1.5,
    borderBottomRightRadius: SIZES.radius_lg * 1.5,
    alignItems: 'center',
    marginBottom: SIZES.margin,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  title: {
    fontSize: SIZES.h3,
    fontFamily: FONTS.h3.fontFamily,
    lineHeight: FONTS.h3.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.title,
    marginBottom: SIZES.margin / 2,
  },
  subtitle: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.white,
    opacity: 0.9,
  },
  cardsContainer: {
    paddingHorizontal: SIZES.padding,
    marginBottom: SIZES.margin,
  },
  card: {
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding,
    marginBottom: SIZES.margin,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SIZES.margin,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderColor,
    paddingBottom: SIZES.padding / 1.5,
  },
  iconContainer: {
    width: SIZES.h3 * 1.5,
    height: SIZES.h3 * 1.5,
    borderRadius: SIZES.radius_lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: SIZES.margin / 1.5,
  },
  phoneIconContainer: {
    backgroundColor: COLORS.primaryLight,
  },
  emailIconContainer: {
    backgroundColor: COLORS.primaryLight,
  },
  locationIconContainer: {
    backgroundColor: COLORS.primaryLight,
  },
  cardTitle: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.primary,
  },
  contactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: SIZES.padding / 1.2,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderColor,
  },
  contactText: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.title,
    flex: 1,
    marginRight: SIZES.margin / 1.5,
  },
  addressContainer: {
    flex: 1,
  },
  hoursContainer: {
    backgroundColor: COLORS.card,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding,
    marginHorizontal: SIZES.padding,
    marginBottom: SIZES.margin,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  hoursTitle: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.primary,
    marginBottom: SIZES.margin,
    textAlign: 'center',
  },
  hoursRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SIZES.padding / 1.5,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderColor,
  },
  hoursDay: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.title,
    fontWeight: FONTS.subheading.fontWeight,
  },
  hoursTime: {
    fontSize: SIZES.fontLg,
    fontFamily: FONTS.fontLg.fontFamily,
    lineHeight: FONTS.fontLg.lineHeight,
    color: COLORS.primary,
    fontWeight: FONTS.heading.fontWeight,
  },
  actionsContainer: {
    backgroundColor: COLORS.card,
    borderRadius: SIZES.radius_lg,
    padding: SIZES.padding,
    marginHorizontal: SIZES.padding,
    shadowColor: COLORS.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 4,
  },
  actionsTitle: {
    fontSize: SIZES.h5,
    fontFamily: FONTS.h5.fontFamily,
    lineHeight: FONTS.h5.lineHeight,
    fontWeight: FONTS.heading.fontWeight,
    color: COLORS.primary,
    marginBottom: SIZES.margin,
    textAlign: 'center',
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  actionButton: {
    alignItems: 'center',
    padding: SIZES.padding / 1.5,
    backgroundColor: COLORS.primaryLight,
    borderRadius: SIZES.radius,
    width: width * 0.25,
  },
  actionText: {
    fontSize: SIZES.fontSm,
    fontFamily: FONTS.fontSm.fontFamily,
    lineHeight: FONTS.fontSm.lineHeight,
    color: COLORS.primary,
    marginTop: SIZES.margin / 2,
    textAlign: 'center',
  },
});